### ISSUE TITLE
Add this repo to npmjs.com

### ISSUE THREAD

**Issue by DasPoet** [filc-dev/rsbuild-plugin-web-extension#10]
Hey there 👋 

First of all, thank you very much for providing this plugin. It has helped me a great deal in getting a basic Chrome plugin up and running with Rsbuild :).

However, I had some trouble finding this repo, because afaict, there is no GitHub link on [npmjs](https://www.npmjs.com/package/rsbuild-plugin-web-extension). Would you mind adding that so other people might have quicker access?

**Comment by eungyeole** [comment]
good!
